# Generated by Django 3.0.7 on 2020-06-30 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_auto_20200630_0923'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Rok produkcji')),
                ('engine', models.PositiveSmallIntegerField(verbose_name='Pojemność')),
                ('fuel', models.CharField(max_length=32, verbose_name='Rodzaj paliwa')),
                ('mileage', models.PositiveIntegerField(verbose_name='Przebieg')),
            ],
        ),
    ]
