# Generated by Django 3.0.7 on 2020-06-30 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_additionaldescription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdditionalDescription',
        ),
        migrations.AddField(
            model_name='car',
            name='engine',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Pojemność'),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel',
            field=models.CharField(blank=True, default='a', max_length=32, verbose_name='Rodzaj paliwa'),
        ),
    ]
