# Generated by Django 3.0.7 on 2020-06-30 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_auto_20200630_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='photos', verbose_name='Zdjęcie'),
        ),
    ]
