# Generated by Django 3.0.7 on 2020-06-30 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_auto_20200630_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='photo2',
        ),
        migrations.RemoveField(
            model_name='car',
            name='photo3',
        ),
        migrations.RemoveField(
            model_name='car',
            name='photo4',
        ),
        migrations.RemoveField(
            model_name='car',
            name='photo5',
        ),
    ]
